# Generated by Django 2.1.4 on 2019-04-12 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='project',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='labels',
        ),
        migrations.DeleteModel(
            name='Label',
        ),
    ]
