# Generated by Django 2.1.4 on 2019-04-12 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='project',
        ),
        migrations.DeleteModel(
            name='Label',
        ),
    ]
