# Generated by Django 2.1.4 on 2019-04-12 11:20

from django.db import migrations, models
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_label'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Label',
        ),
        migrations.AddField(
            model_name='issue',
            name='label',
            field=models.CharField(choices=[(project.models.Label(1), 1), (project.models.Label(2), 2), (project.models.Label(3), 3), (project.models.Label(4), 4)], default='feature', max_length=50),
        ),
    ]
