# Generated by Django 2.1.4 on 2019-04-23 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20190412_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='author',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='label',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='milestone',
        ),
        migrations.AlterField(
            model_name='issue',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='project.Project'),
        ),
        migrations.AlterField(
            model_name='label',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='project.Project'),
        ),
    ]
