# Generated by Django 2.2.4 on 2019-08-15 22:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20190423_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Due date'),
            preserve_default=False,
        ),
    ]
