# Generated by Django 2.2.4 on 2019-08-15 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_issue_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='label',
            field=models.ManyToManyField(to='project.Label'),
        ),
        migrations.AddField(
            model_name='issue',
            name='milestone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.Milestone'),
        ),
    ]
