# Generated by Django 2.2.4 on 2019-08-15 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_auto_20190816_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='label',
            field=models.ManyToManyField(null=True, to='project.Label'),
        ),
    ]
