# Generated by Django 2.2.4 on 2019-08-15 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_auto_20190816_0110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='label',
        ),
        migrations.AddField(
            model_name='issue',
            name='label',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.Label'),
        ),
    ]
