sudo: required
language: python
python:
- 3.5.2

addons:
  apt:
    packages:
    - sshpass
services:
- docker

branches:
- master
- issueCRUD
- homepage
- loginAndRegister
- milestoneCRUD
- labelCrud
- projectCRUD


before_install:
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
- docker --version

install:
- docker images

script:
#- docker-compose up -d
#- python tests.py

#after_success:
#- export SSHPASS=$DEPLOY_PASS
env:
  global:
  - secure: tWM8rtfzwxUZxgwTzzdIxYVASgh6e0k4/HN1fJ20BawrSfYp8SR5q4RaCMxe2MjeVxbwMjaAPrO8iZrpqFRvGYPROrJyj6X3J+OXm2REhIbv634483eyLi0av7XczZd4bvoCluZYJum5FJ/37OxfesTxdbC8mW5uRQHz81Xj4M7GdnMNCb/E5p6LFEMEAmNuygODvqp3uxa5ActtTpxhj/j6H5FFm6bqYfbGWQaZED9w1h5Lm8L3i1NIuD6qbjcuvjiELMceJp21GBZoFJHww5rrBKTWL9Bcq98euDxciTtecPhkegMqdfeDxbKdYY7saDN9/K1Rpd2lGZMs+qxxHKBth/kTEs+XE3fUIUZkvYOkiW0brn4v+Kcnz0/2/ADOepur1f4TVxI5QYlsBXdwr4IcRbWwDHzKy3gvvOXsruSiMlf8DdHmNOj/4mtc30ydSqu08MFnkQgSA0X8YlbLop1KuIA8l7g7mihkB3+N/ji5w/D+1x8/SSQB0EtO3V8G7o+gqMiDwzI+J363HSe85hfp5LH1cPYNJJ2SWY5enK/F9mCqU+A9PAOygIp0UycCbjo7/kzyJJIyqbO0nucdYF5S4ktIQJVnrALx8voskhv+nsnbvEmrEg86GeWNgeHVqmczHeucrbPwYSYepWhki9nHcJ+2EBGX1ni3xhQeOzI=
  - secure: MWIiWMg5PPRnVNHWmTep/lpd0fKD/dWLxODVvp8DYY1QZuQqYupEp13Uik/i+j+qCZ/ObmTOG9KmIuFV4tpEU3wpBig0oDGroazLREzRHLT60OvYMaLc9hnnsGwbGoOsBHcorkIe+JlEtpySufkvZFefWi7Pjebg362NjR2/4J4oMquKp70kqzwis7A5h5nQzInYU+v4zbTd3wyjcGthBAJ0L83r4oCiMiEjDlCDyZoiQDoTifTUtEwkhHABIz2Z8XiQoboxhgvM5WKLlUtCeozqqQjg8O4aTC0PraUN0vXdzVs8zWdTigwRUSd9axHYOmzsK+OKhZWQDdiILi4YhT9Cpllzc/nL54gkGeDn1LaNyJEgqLqwMQ0Z5ngK+zlc7AcQLPJDhRkxooOxC8XGsR5sC+YZJ7FnDli7PQtacUXyAZ96mmnK7R0PtZejpvISGrjeesUaJQgQh4MTxwwObx220p9yVN5xycJK4MImMsvGyGI2txSxxOatpWJDaJ7iS8hV+GRV7qYpnGwg+jw4A2vw5Qi8lxAtiwwiDUQ4GnBVPr4X66WJ5efPomSLjcck6+nYzrBFSGC5sevLhJEHU5nKUcm28c1pQSCUpBIIHiVWwpMFx/0GsMmr3S3xGZ/uwUwLYUATuWcUz+3q6sP5QXG5yw8kbwi90sRKhqiS2fA=
