sudo: required
language: python
python:
  - '3.5.2'

addons:
  apt:
    packages:
    - sshpass
services:
  - docker
  
install:
  - docker images
  - pip install -r requirements.txt

branches:
  - master
  - projectCRUD
  - loginAndRegister
  - issueCRUD
  - milestoneCRUD
  - labelCRUD
  - homepage

before_install:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
  - docker --version
  - docker build -t $DOCKER_USERNAME/uks_projekat:latest .
  - openssl aes-256-cbc -K $encrypted_83630750896a_key -iv $encrypted_83630750896a_iv -in deploy_key.enc -out ./deploy_key -d

script:
  - python tests.py
  - docker-compose up -d
  
after_success:
#  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
  - docker push $DOCKER_USERNAME/uks_projekat:latest
  - export SSHPASS=$DEPLOY_PASS