sudo: required
language: python
python:
- "3.5"
services:
- docker
- postgresql
dist: trusty
branches:
- master
- issueCRUD
- homepage
- loginAndRegister
- milestoneCRUD
- labelCrud
- projectCRUD
before_install:
- docker --version
install:
- pip install -r requirements.txt
script:
  - pytest
after_success:
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
- docker push $DOCKER_USERNAME/uks-projekat:proba

deploy:
  on:
    branch: master

env:
  global:
  - PGPORT=5433
