version: '2'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: postgres

  web:
    build: .
    restart: always
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

