version: '3'

services:
  db:
    container_name: db
    image: postgres
    restart: always

  web:
    container_name: web
    build: .
    command: python manage.py makemigrations
    command: python manage.py migrate
    command: python manage.py runserver 0.0.0.0:8001
    restart: always
    volumes:
      - ./app:/code
    expose:
      - "8001"
    ports:
      - "8001:8001"
    depends_on:
      - db

