# Generated by Django 2.1.4 on 2019-04-12 11:20

from django.db import migrations, models
import projekat.models


class Migration(migrations.Migration):

    dependencies = [
        ('projekat', '0005_label'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Label',
        ),
        migrations.AddField(
            model_name='issue',
            name='label',
            field=models.CharField(choices=[(projekat.models.Label(1), 1), (projekat.models.Label(2), 2), (projekat.models.Label(3), 3), (projekat.models.Label(4), 4)], default='feature', max_length=50),
        ),
    ]
